-- AidPilot Phase 5: starter scholarships with full engine fields
-- Run after 007_phase_5_scholarship_engine.sql
-- Safe to rerun. Uses ON CONFLICT (name) DO NOTHING.

-- Add your admin email (must match NEXT_PUBLIC_ADMIN_EMAILS):
-- insert into public.admin_allowlist (email) values ('your@email.com') on conflict do nothing;

insert into public.scholarship_sources (
  name, provider, amount, deadline, url, application_url, source_url,
  eligible_states, education_levels, student_types, major_keywords, interest_tags, tags,
  eligibility, need_based, merit_based, essay_required, effort_level, source, verified_date, active
)
values
  ('California Community College Promise Grant', 'CA Student Aid Commission', 3500, '2026-08-15', 'https://www.csac.ca.gov/', 'https://www.csac.ca.gov/', 'https://www.csac.ca.gov/', array['CA'], array['undergraduate'], array['College student'], array[]::text[], array['community college'], array['community college', 'california'], 'California residents attending community college.', true, false, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('First-Generation Rising Scholars Award', 'National College Access Network', 2500, '2026-07-30', 'https://example.org/first-gen-rising', 'https://example.org/first-gen-rising/apply', 'https://example.org/first-gen-rising', array[]::text[], array['undergraduate'], array['College student'], array[]::text[], array['first generation'], array['first generation', 'access'], 'Open to first-generation undergraduate students with financial need.', true, false, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('STEM Pathways Undergraduate Grant', 'Future Engineers Foundation', 4000, '2026-08-20', 'https://example.org/stem-pathways', 'https://example.org/stem-pathways/apply', 'https://example.org/stem-pathways', array[]::text[], array['undergraduate'], array['College student'], array['engineering', 'computer science', 'math'], array['stem'], array['stem', 'engineering'], 'Undergraduates pursuing STEM majors with a 3.0+ GPA.', false, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Business Leaders of Tomorrow Scholarship', 'Metro Business Alliance', 3000, '2026-09-01', 'https://example.org/business-leaders', 'https://example.org/business-leaders/apply', 'https://example.org/business-leaders', array['CA', 'NY', 'IL'], array['undergraduate'], array['College student'], array['business', 'finance', 'marketing'], array['business'], array['business', 'leadership'], 'Students interested in business, entrepreneurship, or finance.', false, true, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('No-Essay Quick Apply Grant', 'Student Success Fund', 1500, '2026-07-15', 'https://example.org/quick-grant', 'https://example.org/quick-grant/apply', 'https://example.org/quick-grant', array[]::text[], array['undergraduate'], array['College student'], array[]::text[], array['general'], array['no essay', 'quick apply'], 'General college students; short application, no essay required.', true, false, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('Low-Income Student Bridge Award', 'Access for All Foundation', 3200, '2026-08-10', 'https://example.org/bridge-award', 'https://example.org/bridge-award/apply', 'https://example.org/bridge-award', array[]::text[], array['undergraduate'], array['College student'], array[]::text[], array['low income'], array['need-based', 'bridge'], 'Demonstrated financial need; Pell-eligible students encouraged.', true, false, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Transfer Excellence Scholarship', 'National Transfer Network', 2800, '2026-08-25', 'https://example.org/transfer-excellence', 'https://example.org/transfer-excellence/apply', 'https://example.org/transfer-excellence', array['CA', 'TX'], array['undergraduate'], array['College student'], array[]::text[], array['transfer'], array['transfer', 'community college'], 'Community college students transferring to a four-year university.', true, true, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('California Undergraduate Merit Award', 'Golden State Scholars', 5000, '2026-07-28', 'https://example.org/ca-merit', 'https://example.org/ca-merit/apply', 'https://example.org/ca-merit', array['CA'], array['undergraduate'], array['College student'], array[]::text[], array['merit'], array['california', 'merit'], 'California residents with strong academic records.', false, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Health Careers Starter Scholarship', 'Regional Health Trust', 3500, '2026-09-05', 'https://example.org/health-starter', 'https://example.org/health-starter/apply', 'https://example.org/health-starter', array['CA', 'AZ'], array['undergraduate'], array['College student'], array['nursing', 'public health', 'pre-med'], array['health'], array['health careers'], 'Students planning careers in nursing, public health, or medicine.', true, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Women in Tech Scholarship', 'Code Forward Initiative', 4500, '2026-08-18', 'https://example.org/women-in-tech', 'https://example.org/women-in-tech/apply', 'https://example.org/women-in-tech', array[]::text[], array['undergraduate', 'graduate'], array['College student'], array['computer science', 'information technology'], array['technology', 'women'], array['women', 'stem'], 'Women studying computer science or related technology fields.', false, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Community Service Impact Award', 'Serve & Succeed Fund', 2000, '2026-07-20', 'https://example.org/service-impact', 'https://example.org/service-impact/apply', 'https://example.org/service-impact', array[]::text[], array['undergraduate'], array['College student', 'High school student'], array[]::text[], array['community service'], array['service', 'leadership'], 'Students with meaningful community service experience.', true, true, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('General College Student Grant', 'Open Door Scholarships', 1200, '2026-09-15', 'https://example.org/open-door', 'https://example.org/open-door/apply', 'https://example.org/open-door', array[]::text[], array['undergraduate'], array['College student'], array[]::text[], array['general'], array['general', 'college'], 'Any enrolled undergraduate student at an accredited institution.', false, false, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('Southern California Regional Award', 'SoCal Education Fund', 2200, '2026-07-25', 'https://example.org/socal-regional', 'https://example.org/socal-regional/apply', 'https://example.org/socal-regional', array['CA'], array['undergraduate'], array['College student'], array[]::text[], array['regional'], array['southern california'], 'Residents of Southern California counties attending college.', true, false, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Biology Research Starter Grant', 'Life Sciences Society', 2800, '2026-09-10', 'https://example.org/bio-research', 'https://example.org/bio-research/apply', 'https://example.org/bio-research', array[]::text[], array['undergraduate'], array['College student'], array['biology', 'biochemistry'], array['research'], array['biology', 'research'], 'Undergraduates interested in biological sciences or lab research.', false, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Creative Arts Talent Scholarship', 'Arts for Students Fund', 1800, '2026-08-30', 'https://example.org/arts-talent', 'https://example.org/arts-talent/apply', 'https://example.org/arts-talent', array[]::text[], array['undergraduate'], array['College student'], array['art', 'music', 'theater'], array['arts'], array['creative', 'essay'], 'Students pursuing creative arts with a portfolio or essay.', false, true, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Pell-Eligible Opportunity Fund', 'Federal Aid Partners', 2000, '2026-08-05', 'https://example.org/pell-opportunity', 'https://example.org/pell-opportunity/apply', 'https://example.org/pell-opportunity', array[]::text[], array['undergraduate'], array['College student'], array[]::text[], array['pell'], array['pell', 'need-based'], 'Students who receive or qualify for Federal Pell Grant.', true, false, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('High School Senior College Prep Award', 'Next Step Foundation', 1000, '2026-07-12', 'https://example.org/senior-prep', 'https://example.org/senior-prep/apply', 'https://example.org/senior-prep', array[]::text[], array['high school'], array['High school student'], array[]::text[], array['college prep'], array['high school'], 'High school seniors planning to enroll in college next fall.', true, false, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Texas First-Year Opportunity Grant', 'Lone Star Education Fund', 2500, '2026-08-08', 'https://example.org/tx-first-year', 'https://example.org/tx-first-year/apply', 'https://example.org/tx-first-year', array['TX'], array['undergraduate'], array['College student', 'High school student'], array[]::text[], array['texas'], array['texas', 'first year'], 'Texas residents entering their first year of college.', true, false, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Florida Sunshine Merit Scholarship', 'Sunshine State Scholars', 3000, '2026-08-12', 'https://example.org/fl-merit', 'https://example.org/fl-merit/apply', 'https://example.org/fl-merit', array['FL'], array['undergraduate'], array['College student'], array[]::text[], array['merit'], array['florida', 'merit'], 'Florida residents with merit-based academic achievement.', false, true, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('Computer Science Future Leaders Award', 'Tech Talent Pipeline', 4200, '2026-09-01', 'https://example.org/cs-leaders', 'https://example.org/cs-leaders/apply', 'https://example.org/cs-leaders', array[]::text[], array['undergraduate'], array['College student'], array['computer science', 'software engineering'], array['technology'], array['stem', 'computer science'], 'CS majors passionate about technology and leadership.', false, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Parent Scholar Support Grant', 'Family Forward Fund', 1500, '2026-08-22', 'https://example.org/parent-scholar', 'https://example.org/parent-scholar/apply', 'https://example.org/parent-scholar', array[]::text[], array['undergraduate'], array['Parent'], array[]::text[], array['parent'], array['parent', 'nontraditional'], 'Parents balancing college coursework with family responsibilities.', true, false, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('Environmental Stewardship Scholarship', 'Green Campus Alliance', 2600, '2026-09-08', 'https://example.org/green-campus', 'https://example.org/green-campus/apply', 'https://example.org/green-campus', array[]::text[], array['undergraduate'], array['College student'], array['environmental science', 'sustainability'], array['environment'], array['sustainability', 'stem'], 'Students interested in environmental science or sustainability.', false, true, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Rotary Local Leaders Award', 'District 5320 Rotary', 1400, '2026-07-18', 'https://example.org/rotary-local', 'https://example.org/rotary-local/apply', 'https://example.org/rotary-local', array['CA', 'OR', 'WA'], array['undergraduate', 'high school'], array['College student', 'High school student'], array[]::text[], array['leadership'], array['rotary', 'local'], 'Local students demonstrating leadership and community involvement.', true, true, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('Dream Act California Support Fund', 'Immigrant Student Alliance', 3800, '2026-08-28', 'https://example.org/dream-act-ca', 'https://example.org/dream-act-ca/apply', 'https://example.org/dream-act-ca', array['CA'], array['undergraduate'], array['College student'], array[]::text[], array['dream act'], array['california', 'dream act'], 'California Dream Act eligible students pursuing higher education.', true, false, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Graduate Research Fellowship Sample', 'National Grad Fund', 6000, '2026-09-20', 'https://example.org/grad-research', 'https://example.org/grad-research/apply', 'https://example.org/grad-research', array[]::text[], array['graduate'], array['College student'], array['research'], array['graduate'], array['graduate', 'research'], 'Graduate students engaged in thesis or dissertation research.', false, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Work-Study Support Micro-Grant', 'Campus Employment Fund', 1000, '2026-09-05', 'https://example.org/work-study-grant', 'https://example.org/work-study-grant/apply', 'https://example.org/work-study-grant', array[]::text[], array['undergraduate'], array['College student'], array[]::text[], array['employment'], array['work-study'], 'Students balancing part-time work with full-time study.', true, false, false, 'low', 'phase5_seed', '2026-06-01', true),
  ('Public Policy Essay Scholarship', 'Civic Future Institute', 2400, '2026-08-15', 'https://example.org/policy-essay', 'https://example.org/policy-essay/apply', 'https://example.org/policy-essay', array[]::text[], array['undergraduate'], array['College student'], array['political science', 'public policy'], array['civic engagement'], array['essay', 'policy'], 'Essay on a public policy issue affecting students.', false, true, true, 'high', 'phase5_seed', '2026-06-01', true),
  ('Nursing Pathway Award', 'Care Forward Health', 3400, '2026-09-12', 'https://example.org/nursing-pathway', 'https://example.org/nursing-pathway/apply', 'https://example.org/nursing-pathway', array['CA', 'TX', 'FL'], array['undergraduate'], array['College student'], array['nursing'], array['health'], array['nursing', 'health'], 'Nursing students committed to community healthcare.', true, true, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Mathematics Excellence Grant', 'Pi Foundation', 2700, '2026-08-02', 'https://example.org/math-excellence', 'https://example.org/math-excellence/apply', 'https://example.org/math-excellence', array[]::text[], array['undergraduate'], array['College student'], array['mathematics', 'statistics'], array['stem'], array['math', 'stem'], 'Undergraduates majoring in mathematics or statistics.', false, true, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('Rural Student Access Scholarship', 'Heartland Education Trust', 2100, '2026-07-30', 'https://example.org/rural-access', 'https://example.org/rural-access/apply', 'https://example.org/rural-access', array[]::text[], array['undergraduate'], array['College student'], array[]::text[], array['rural'], array['rural', 'access'], 'Students from rural communities with financial need.', true, false, true, 'medium', 'phase5_seed', '2026-06-01', true),
  ('UC Transfer Success Fund', 'University Access Partners', 4500, '2026-08-05', 'https://example.org/uc-transfer', 'https://example.org/uc-transfer/apply', 'https://example.org/uc-transfer', array['CA'], array['undergraduate'], array['College student'], array[]::text[], array['transfer'], array['uc', 'transfer'], 'California transfer students aiming for UC campuses.', true, true, true, 'high', 'phase5_seed', '2026-06-01', true)
on conflict (name) do nothing;

-- Backfill Phase 5 fields on legacy sample rows when still null
update public.scholarship_sources
set
  application_url = coalesce(application_url, url),
  source_url = coalesce(source_url, url),
  verified_date = coalesce(verified_date, '2026-06-01'::date),
  effort_level = coalesce(effort_level, case when essay_required then 'medium' else 'low' end),
  eligibility = coalesce(eligibility, 'Verify eligibility with the scholarship provider.')
where source = 'sample' or source is null;
