import type { FafsaWorkflowStep } from "@/lib/types";

export type FafsaWorkflowStepSeed = Omit<FafsaWorkflowStep, "id" | "created_at">;

export const FAFSA_WORKFLOW_STEP_SEEDS: FafsaWorkflowStepSeed[] = [
  {
    step_order: 1,
    title: "Create StudentAid.gov account",
    description: "Set up your FSA ID at StudentAid.gov before starting the FAFSA.",
    category: "Account",
    applies_to: "all",
    default_priority: "high",
    source_url: "https://studentaid.gov",
  },
  {
    step_order: 2,
    title: "Gather student and contributor information",
    description: "Collect Social Security numbers, tax info, and school codes. AidPilot does not store this data.",
    category: "Preparation",
    applies_to: "all",
    default_priority: "high",
    source_url: "https://studentaid.gov/h/apply-for-aid/fafsa",
  },
  {
    step_order: 3,
    title: "Invite contributor if needed",
    description: "If a parent or spouse must provide information, invite them through StudentAid.gov.",
    category: "Contributors",
    applies_to: "dependent",
    default_priority: "high",
    source_url: null,
  },
  {
    step_order: 4,
    title: "Complete FAFSA",
    description: "Fill out all required FAFSA sections on StudentAid.gov.",
    category: "Application",
    applies_to: "all",
    default_priority: "high",
    source_url: null,
  },
  {
    step_order: 5,
    title: "Submit FAFSA",
    description: "Review and submit your FAFSA before your state and school priority deadlines.",
    category: "Application",
    applies_to: "all",
    default_priority: "high",
    source_url: null,
  },
  {
    step_order: 6,
    title: "Review FAFSA Submission Summary",
    description: "Save your Submission Summary and confirm your Student Aid Index (SAI).",
    category: "Review",
    applies_to: "all",
    default_priority: "medium",
    source_url: null,
  },
  {
    step_order: 7,
    title: "Fix errors or corrections if needed",
    description: "If your school or FAFSA flags errors, make corrections on StudentAid.gov.",
    category: "Corrections",
    applies_to: "all",
    default_priority: "high",
    source_url: null,
  },
  {
    step_order: 8,
    title: "Watch for school verification request",
    description: "Check your email and school aid portal for verification selection notices.",
    category: "Verification",
    applies_to: "all",
    default_priority: "high",
    source_url: null,
  },
  {
    step_order: 9,
    title: "Submit requested verification documents",
    description: "Upload verification forms through your school portal, not through AidPilot.",
    category: "Verification",
    applies_to: "all",
    default_priority: "high",
    source_url: null,
  },
  {
    step_order: 10,
    title: "Check school financial aid portal",
    description: "Log into your school aid portal for messages, holds, and document requests.",
    category: "School portal",
    applies_to: "all",
    default_priority: "medium",
    source_url: null,
  },
  {
    step_order: 11,
    title: "Compare aid offers",
    description: "Review grants, scholarships, loans, and work-study from each school you are considering.",
    category: "Aid offer",
    applies_to: "all",
    default_priority: "medium",
    source_url: null,
  },
  {
    step_order: 12,
    title: "Contact financial aid office if aid is not enough",
    description: "Ask your school about appeal options, emergency aid, or additional scholarships. Verify deadlines with your aid office.",
    category: "Appeal",
    applies_to: "all",
    default_priority: "medium",
    source_url: null,
  },
];
