import type { ScholarshipSource } from "@/lib/types";

export type ScholarshipSourceSeed = Omit<ScholarshipSource, "id" | "created_at">;

/** Starter/sample scholarships. Replace with real data sources later. */
export const SCHOLARSHIP_SOURCE_SEEDS: ScholarshipSourceSeed[] = [
  { name: "California Dream Act Scholarship Fund", provider: "Sample CA Foundation", amount: 5000, deadline: "2026-07-18", url: null, eligible_states: ["CA"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["dream act", "california"], need_based: true, merit_based: false, essay_required: true, min_gpa: 2.5, source: "sample", active: true },
  { name: "First-Gen College Success Award", provider: "Sample National Fund", amount: 2500, deadline: "2026-08-01", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["first generation"], need_based: true, merit_based: false, essay_required: true, min_gpa: 2.0, source: "sample", active: true },
  { name: "STEM Future Leaders Grant", provider: "Sample STEM Alliance", amount: 4000, deadline: "2026-07-25", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: ["stem", "engineering", "science"], tags: ["stem"], need_based: false, merit_based: true, essay_required: true, min_gpa: 3.0, source: "sample", active: true },
  { name: "Women in Engineering Scholarship", provider: "Sample Women in Tech", amount: 3500, deadline: "2026-08-20", url: null, eligible_states: [], education_levels: ["undergraduate", "graduate"], student_types: ["College student"], major_keywords: ["engineering"], tags: ["women", "stem"], need_based: false, merit_based: true, essay_required: true, min_gpa: 3.0, source: "sample", active: true },
  { name: "Community Service Leaders Award", provider: "Sample Service Network", amount: 1500, deadline: "2026-07-14", url: null, eligible_states: ["CA", "AZ", "NV"], education_levels: ["undergraduate"], student_types: ["College student", "High school student"], major_keywords: [], tags: ["community service"], need_based: true, merit_based: true, essay_required: true, min_gpa: 2.5, source: "sample", active: true },
  { name: "Transfer Student Bridge Grant", provider: "Sample Transfer Fund", amount: 3000, deadline: "2026-08-05", url: null, eligible_states: ["CA"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["transfer"], need_based: true, merit_based: false, essay_required: false, min_gpa: 2.5, source: "sample", active: true },
  { name: "Pell Match Opportunity", provider: "Sample Access Fund", amount: 2000, deadline: "2026-08-15", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["pell", "need-based"], need_based: true, merit_based: false, essay_required: false, min_gpa: null, source: "sample", active: true },
  { name: "Golden State Essay Award", provider: "Sample CA Writers Guild", amount: 1000, deadline: "2026-07-19", url: null, eligible_states: ["CA"], education_levels: ["undergraduate"], student_types: ["College student", "High school student"], major_keywords: ["writing", "english"], tags: ["essay"], need_based: false, merit_based: true, essay_required: true, min_gpa: 3.0, source: "sample", active: true },
  { name: "SoCal Service Scholarship", provider: "Sample Regional Fund", amount: 1800, deadline: "2026-07-16", url: null, eligible_states: ["CA"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["service", "southern california"], need_based: true, merit_based: false, essay_required: true, min_gpa: 2.5, source: "sample", active: true },
  { name: "Local Rotary Club Award", provider: "Sample Rotary District", amount: 1200, deadline: "2026-07-22", url: null, eligible_states: ["CA", "OR", "WA"], education_levels: ["undergraduate", "high school"], student_types: ["College student", "High school student"], major_keywords: [], tags: ["local", "rotary"], need_based: true, merit_based: true, essay_required: false, min_gpa: 2.5, source: "sample", active: true },
  { name: "CSU Transfer Excellence Award", provider: "Sample CSU Foundation", amount: 2500, deadline: "2026-08-30", url: null, eligible_states: ["CA"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["csu", "transfer"], need_based: false, merit_based: true, essay_required: true, min_gpa: 3.2, source: "sample", active: true },
  { name: "Biology Research Starter Grant", provider: "Sample Bio Society", amount: 2200, deadline: "2026-09-15", url: null, eligible_states: [], education_levels: ["undergraduate", "graduate"], student_types: ["College student"], major_keywords: ["biology", "research"], tags: ["biology", "research"], need_based: false, merit_based: true, essay_required: true, min_gpa: 3.3, source: "sample", active: true },
  { name: "Public Health Pathways Award", provider: "Sample Health Fund", amount: 2800, deadline: "2026-09-10", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: ["public health", "nursing"], tags: ["health"], need_based: true, merit_based: false, essay_required: true, min_gpa: 3.0, source: "sample", active: true },
  { name: "Low-Income Bridge Scholarship", provider: "Sample Access Network", amount: 3500, deadline: "2026-08-25", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["low income", "need-based"], need_based: true, merit_based: false, essay_required: false, min_gpa: 2.0, source: "sample", active: true },
  { name: "Creative Writing Talent Award", provider: "Sample Arts Council", amount: 1500, deadline: "2026-09-20", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: ["writing", "creative"], tags: ["arts", "essay"], need_based: false, merit_based: true, essay_required: true, min_gpa: 2.8, source: "sample", active: true },
  { name: "Campus Employment Support Grant", provider: "Sample Work-Study Fund", amount: 1000, deadline: "2026-09-05", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["work-study", "employment"], need_based: true, merit_based: false, essay_required: false, min_gpa: null, source: "sample", active: true },
  { name: "Health Careers Starter Award", provider: "Sample Medical Foundation", amount: 3200, deadline: "2026-09-12", url: null, eligible_states: ["CA", "TX", "FL"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: ["health", "pre-med", "nursing"], tags: ["health careers"], need_based: true, merit_based: true, essay_required: true, min_gpa: 3.0, source: "sample", active: true },
  { name: "Anteater Excellence Scholarship", provider: "Sample UC Foundation", amount: 5000, deadline: "2026-07-12", url: null, eligible_states: ["CA"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["uc", "merit"], need_based: false, merit_based: true, essay_required: true, min_gpa: 3.5, source: "sample", active: true },
  { name: "Irvine Transfer Success Fund", provider: "Sample OC Foundation", amount: 2800, deadline: "2026-08-05", url: null, eligible_states: ["CA"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["transfer", "orange county"], need_based: true, merit_based: false, essay_required: true, min_gpa: 3.0, source: "sample", active: true },
  { name: "FG STEM Accelerator", provider: "Sample STEM Access", amount: 4500, deadline: "2026-08-10", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: ["stem", "computer science", "math"], tags: ["first generation", "stem"], need_based: true, merit_based: true, essay_required: true, min_gpa: 3.0, source: "sample", active: true },
  { name: "High School to College Bridge Award", provider: "Sample Prep Fund", amount: 1000, deadline: "2026-07-30", url: null, eligible_states: [], education_levels: ["high school"], student_types: ["High school student"], major_keywords: [], tags: ["high school"], need_based: true, merit_based: false, essay_required: true, min_gpa: 2.5, source: "sample", active: true },
  { name: "Graduate Research Fellowship (Sample)", provider: "Sample Grad Fund", amount: 6000, deadline: "2026-09-01", url: null, eligible_states: [], education_levels: ["graduate"], student_types: ["College student"], major_keywords: ["research"], tags: ["graduate", "research"], need_based: false, merit_based: true, essay_required: true, min_gpa: 3.5, source: "sample", active: true },
  { name: "Parent Advocate Education Grant", provider: "Sample Family Fund", amount: 800, deadline: "2026-08-18", url: null, eligible_states: [], education_levels: ["undergraduate"], student_types: ["Parent"], major_keywords: [], tags: ["parent"], need_based: true, merit_based: false, essay_required: false, min_gpa: null, source: "sample", active: true },
  { name: "Texas First-Year Opportunity", provider: "Sample TX Fund", amount: 2000, deadline: "2026-07-28", url: null, eligible_states: ["TX"], education_levels: ["undergraduate"], student_types: ["College student", "High school student"], major_keywords: [], tags: ["texas"], need_based: true, merit_based: false, essay_required: true, min_gpa: 2.5, source: "sample", active: true },
  { name: "Florida Sunshine Merit Award", provider: "Sample FL Foundation", amount: 2500, deadline: "2026-08-08", url: null, eligible_states: ["FL"], education_levels: ["undergraduate"], student_types: ["College student"], major_keywords: [], tags: ["florida", "merit"], need_based: false, merit_based: true, essay_required: false, min_gpa: 3.2, source: "sample", active: true },
];
